### ISSUE TITLE
Decide on how to combine or group Test Samples

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/ClientSim#10]
We made a separate test to fix #3 - handy for easily developing and testing, but this will become unwieldy if we make a separate one for each issue.

**Comment by CyanLaser** [comment]
The original test sample was intended for users to be able to use it as an example for creating their own world tests. With that in mind, my impression would be that it should remain as a user example and that all new tests intended for verifying client sim itself should be in their own separate sample. Users will never need to see this unless they want to learn about testing client sim code.

**Comment by momo-the-monster** [comment]
Refactored this in #26
