### ISSUE TITLE
ClientSim causes UdonRuntimeExceptions on code related to avatar scaling

### ISSUE THREAD

**Issue by Reimajo** [vrchat-community/ClientSim#101]
ClientSim 1.2.6 causes issues when used together with the newest VRCSDK and UdonSharp and using their new features.

For example, the following UdonSharp code will throw an exception:
```
void Start()
{
       float maxHeight = Networking.LocalPlayer.GetAvatarEyeHeightMaximumAsMeters();
}       
```
Other code related to avatar scaling also does.

![grafik](https://github.com/vrchat-community/ClientSim/assets/59415342/975741b2-90dd-4ccb-adcc-c423a10bca15)

**Comment by momo-the-monster** [comment]
Fixed in [ClientSim 1.2.7](https://clientsim.docs.vrchat.com/news/release-1.2.7), just released!
