### ISSUE TITLE
Issues with exiting playmode if ClientSim can't start

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/ClientSim#15]
From @CyanLaser on #9: 

Exiting playmode when there is an exception makes sense for the general use case. My only concern would be when someone is trying something unexpected with a VRChat project. For example, if there is no world descriptor because the scene open isn't a vrchat world, pressing playmode will now instantly exit instead of logging something but allowing the user to continue anyway. In that case, the user can open the settings to disable ClientSim, but just a little extra friction. Hopefully people can discover the settings menu under the VRChat/Utilities since that isn't as intuitive.

**Comment by cubedparadox** [comment]
I'm closing this issue out, as it's covered by https://github.com/vrchat-community/ClientSim/issues/60, which is slated for the next release
