### ISSUE TITLE
[1.1.3] Viewing ClientSim Settings Window adds wordwrap to the Editor Label Gui Style

### ISSUE THREAD

**Issue by CyanLaser** [vrchat-community/ClientSim#28]
Viewing the ClientSim settings window will change the Editor Gui style for all labels to make them word wrap. Once changed, it will not change back. This change persists even after assembly reload.

One example of a label that gets affected by this is the "static" text. It is now overflowing and wrapping when it shouldn't. 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/50863419/168946680-3a1b7d2b-efb0-428e-99fd-86976d0bab60.png">

The exact issue can be found in ClientSimSettingsWindow.cs line 100
https://github.com/vrchat-community/ClientSim/blob/546c6a0a64e468745aa6bce51b1fca15ad5d4b69/Packages/com.vrchat.ClientSim/Editor/Windows/ClientSimSettingsWindow.cs#L100-L101

Please create a new gui style from the old one to prevent editing unity styles.
```cs
_multilineLabel = new GUIStyle(EditorStyles.label); 
```

**Comment by cubedparadox** [comment]
this appears to already be fixed!
