### ISSUE TITLE
[1.1.0] VRCPlayerApi.Respawn crashes Udon

### ISSUE THREAD

**Issue by CyanLaser** [vrchat-community/ClientSim#3]
[VRCSDK version 3.0.1](https://github.com/vrchat/packages/releases/tag/3.0.1) introduced new nodes in Udon to call VRCPlayerApi.Respawn to respawn the local player. When called with ClientSim v1.1.0 the UdonBehaviour will crash. 

Please add support for this node in ClientSim.

```
VRC.Udon.VM.UdonVMException: The VM encountered an error!
Exception Message:
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__Respawn__SystemVoid'.
      Parameter Addresses: 0x00000005
  
  Object reference not set to an instance of an object
[...]
----------------------
Inner Exception:
 ---> VRC.Udon.VM.UdonVMException: An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__Respawn__SystemVoid'.
    Parameter Addresses: 0x00000005
 ---> System.NullReferenceException: Object reference not set to an instance of an object
  at VRC.SDKBase.VRCPlayerApi.Respawn () [0x00000] in <349cbe5ee4824c6cb1f025b4eeb1c313>:0 
  at VRC.Udon.Wrapper.Modules.ExternVRCSDKBaseVRCPlayerApi.__Respawn__SystemVoid (VRC.Udon.Common.Interfaces.IUdonHeap heap, System.Span`1[T] parameterAddresses) [0x0000f] in <35c7e2da117043e9b9d7833b6ff53103>:0 
  at VRC.Udon.VM.UdonVM.Interpret () [0x00273] in <bee69903f99544ebbfc976c4454559cd>:0 
   --- End of inner exception stack trace ---
[...]
```

**Comment by momo-the-monster** [comment]
@CyanLaser thanks for bringing this to my attention. I'd like to make a test for this issue to start, but my attempt at adding it to a new World Test has not gotten very far. Can you describe how you would make a test for this?

**Comment by CyanLaser** [comment]
@momo-the-monster I can think of two ways to test this:
- Create a new integration test case in ClientSimPlayerApiTests similar to the [current Respawn test](https://github.com/vrchat-community/ClientSim/blob/main/Tests/Runtime/IntegrationTests/ClientSimPlayerApiTests.cs#L526-L570). This method would call the actions directly in C# and does not test if udon would crash. This would easily catch the "method not implemented" case or any other exception in trying to call the method.
- Create a new world test based on the sample package included. This would require creating a small test world and udon programs to try calling the suggested methods. I never verified if an udon crash would fail the test though.

**Comment by CyanLaser** [comment]
Making a note that the last sdk added both the `Respawn` and `RespawnWithIndex` nodes. Only the `Respawn` node was mentioned in this bug issue, but both will need an implementation to prevent crashing UdonBehaviours.
