### ISSUE TITLE
[1.1.3] UI is not interactable when moved into Canvas that has no VRCUIShape script

### ISSUE THREAD

**Issue by jacklul** [vrchat-community/ClientSim#30]
The moved Canvas does have the VRCUIShape script and the whole thing works in-game and with CyanEmu.

[UIIssueTest.unitypackage.zip](https://github.com/vrchat-community/ClientSim/files/8714901/UIIssueTest.unitypackage.zip)

**Comment by momo-the-monster** [comment]
Should be fixed as of ClientSim 1.2.2.
