### ISSUE TITLE
Cannot perform upm operation: Unable to add package

### ISSUE THREAD

**Issue by PL-PeaceLight** [vrchat-community/ClientSim#5]
I'm trying to add the package by using git url. Like in the instruction, but I keep getting this error...

`Cannot perform upm operation: Unable to add package [https://github.com/vrchat-community/ClientSim.git]:
  One or more dependencies could not be added to the local file system:
    com.unity.xr.oculus.standalone: EPERM: operation not permitted, unlink ....\Library\PackageCache\com.unity.xr.oculus.standalone@2.38.4\Plugins\x86_64\AudioPluginOculusSpatializer.dll' [NotFound]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
`
Any chance we can get package format instead?

**Comment by momo-the-monster** [comment]
Do you have a conflicting version of the Oculus package? What version is in your project? Which VRC SDK versions do you have in the project?

**Comment by PL-PeaceLight** [comment]
I'm using the latest VRC SDK3 16.19.13 on Unity 2019.

**Comment by momo-the-monster** [comment]
> I'm using the latest VRC SDK3 16.19.13 on Unity 2019.

This repo only works with the git versions of the SDK. You'll need to add them first. If you don't have access to them, then please wait for the release of the VRChat Creator Companion.
