### ISSUE TITLE
Idea : Add a VR based player controller

### ISSUE THREAD

**Issue by stayandwait** [vrchat-community/ClientSim#54]
First of all. I love the addition of the desktop based player controller, works well for desktop VRChat, grabbles, stations, interacts, etc. However, it would be cool if a VR based player controller was added as well, that way VR based objectives could be tested and achieved within the range of development. The existing player height feature would also have more of a use, as we usually adjust the height of the player while in VR.

**Comment by momo-the-monster** [comment]
Thanks for the suggestion, this has already been tracked here: #48.
