### ISSUE TITLE
ClientSim UI intersects with world geometry

### ISSUE THREAD

**Issue by Faxmashine** [vrchat-community/ClientSim#58]
ClientSim's menu can intersect with world geometry, occasionally making it difficult to interact with.

It should instead be rendered in front of all other objects in the scene.
![image](https://user-images.githubusercontent.com/117199600/205381636-bf5635ff-b96d-4c92-930c-d8828a9bd9af.png)
Thank you Rackshaw from our official Discord server for reporting this issue.

**Comment by RackshawGames** [comment]
Incase any details are needed: 
- World geometry is set on the default layer. 
- Using Creator Companion and importing Client Sim via the default official packages. 
- This happens on random projects, once it happens nothing I can do fixes the issue (Re-install etc).
- Client sim does NOT turn off "EditorOnly" tagged Items even with this setting checked in the menu.
- No Errors in console when running.

Can't think of any other issues that may be effecting this, I know a few others have ran into this issues on random projects, with the same items I mentioned above.

**Comment by Faxmashine** [comment]
@MrQ89 , I'm able to reproduce this by removing references to Unity's `Default UI Material`.
![IGLk7fzmOf](https://user-images.githubusercontent.com/117199600/215840660-a2a0cc75-eeaf-4e72-bd37-f6d46832b35c.png)

Not sure what would cause that to happen, but I couldn't find any other way to reproduce the issue. We should be able to fix it by using our own UI material instead of Unity's.

**Comment by RiskyKen** [comment]
After a lot of messing around it seems the editor extension [Awesome Folders](https://assetstore.unity.com/packages/tools/gui/awesome-folders-132885) is conflicting with ClientSim. Removing it from any of my projects with this issue fixes it and adding it to a new projects creates the issues.

**Comment by Faxmashine** [comment]
@RackshawGames, were you using any tools such as Awesome Folders?

**Comment by RiskyKen** [comment]
Tested this a bit more. The canvas background material is still linked for me and the shaders settings look like they are default, also tried making a custom one with the `UI/Default` shader on it and got the same result. Sometimes when Awesome Folders is imported everything works fine, so am not sure if it's just it or some weird combination of other factors.

For myself I have just switch over to [Rainbow Folders 2](https://assetstore.unity.com/packages/tools/utilities/rainbow-folders-2-143526), it's doing most of the things I wanted from Awesome Folders.

Default material and it's settings.
![image](https://user-images.githubusercontent.com/5360809/216400319-c94c76be-1edc-4398-bf54-9a7e3aafd542.png)

Custom material.
![image](https://user-images.githubusercontent.com/5360809/216399321-2b622d20-aa10-40de-b2d3-ad44252519b2.png)

**Comment by RackshawGames** [comment]
@Faxmashine That is correct I am using the AwesomeFolders unity plugin as Risky mentioned!

**Comment by Faxmashine** [comment]
Hah, well there's our solution 😄 I suppose AwesomeFolders interferes with ClientSim somehow. Strange.
This might not be a high-priority task for us to solve, but I'm glad we've tracked down the issue.

Thank you @RiskyKen !

**Comment by cubedparadox** [comment]
I've done some testing, and have found a good enough workaround for this issue!
Reimport any shader file in your project, and the bug will go away until you reimport the AwesomeFolders package. This consistently resolves the bug for me, until I reimport AwesomeFolders afterwards again, which reintroduces the bug. 

This is low-priority, and I wasn't able to find a better fix while testing, so we're closing this bug out!
