### ISSUE TITLE
Play mode Stopped because: Cannot start ClientSim if there is no world descriptor!

### ISSUE THREAD

**Issue by float3** [vrchat-community/ClientSim#60]
[CyanEmu just printed a error message and went into play mode anyways](https://github.com/CyanLaser/CyanEmu/blob/master/CyanEmu/Scripts/CyanEmuMain.cs) 

[ClientSim exits playmode](https://github.com/vrchat-community/ClientSim/blob/main/Packages/com.vrchat.ClientSim/Runtime/System/ClientSimMain.cs#L101) which hinder fast iteration and prevents development on non VRC related Scenes.

**Comment by s-ilent** [comment]
This makes debugging shader effects a total pain. If all I want to do is throw something into playmode to verify that Udon scripts interact with it correctly, the last thing I want to screw around with is getting a scene descriptor up and running and squishing up whatever freakouts ClientSim has about random nonsense.

**Comment by float3** [comment]
I'm willing to pr this, any kind of response would be nice

**Comment by Gulfick** [comment]
Same. Really annoing. Can you fix it please?

**Comment by pema99** [comment]
You can disable client sim in the client sim options, FWIW. Still a bit annoying to juggle it on and off depending on the scene.

**Comment by yatuesday** [comment]
I saw the same error message, and my **VRC Scene Descriptor** disappeared, so I couldn't preview the effect in Unity. So I clicked on **VRChat SDK -> Reload SDK**, and then found the **VRC Scene Descriptor** appeared again, so I can preview the effect in Unity now again.

**Comment by momo-the-monster** [comment]
Fixed in [ClientSim 1.2.6](https://64e5216b21920b27790be4ef--vrc-clientsim.netlify.app/news/release-1.2.6).
