### ISSUE TITLE
ClientSim removes all UI events on a UI component when one or more events are not allowed in Udon

### ISSUE THREAD

**Issue by techanon** [vrchat-community/ClientSim#64]
For example, let's say you have a dropdown that you are trying to mirror onto a TMP_Dropdown (a type which is not allowed in Udon currently) by updating it's value but then have another UI event like a SendCustomEvent (one that _is_ valid). Regardless of the different legalities of each UI event, client sim purges _all_ events.

It really should check for which indexes violate the Udon restrictions and only purge those indices instead of everything.

**Comment by cubedparadox** [comment]
Thanks for the bug report! This is actually an SDK bug, not a ClientSim issue, so I'm going to close out the issue; feel free to report it as an SDK bug on our [canny](https://feedback.vrchat.com/sdk-bug-reports)!

**Comment by techanon** [comment]
Canny created https://feedback.vrchat.com/sdk-bug-reports/p/sdk-removes-all-ui-events-on-a-ui-component-when-one-or-more-events-are-not-allo
