### ISSUE TITLE
ClientSim should give more information when no spawn point is set

### ISSUE THREAD

**Issue by techanon** [vrchat-community/ClientSim#8]
Related to issue #7 if a user is trying to use ClientSim with no spawn points available, it'd be good to have clearer/more obvious messaging to the user as to the root cause of the problem.

**Comment by momo-the-monster** [comment]
@techanon with the above change, if you start ClientSim with Player Spawning turned on but no spawn points available, Playback will be stopped and you'll see this message:
![image](https://user-images.githubusercontent.com/737888/161148671-cdf48423-c8ba-4e86-845c-6af8bfb8b9a0.png)
