### ISSUE TITLE
Clientsim play mode not working after latest update.

### ISSUE THREAD

**Issue by Necatron1980** [vrchat-community/ClientSim#89]
I've run into some sort of error relating to the Vrc Clientsim player mode.

My world was working fine up until I updated it to the latest client requirements.

The play button wont show the vrc emulation for testing which means I can't test anything.

**Comment by momo-the-monster** [comment]
@Necatron1980 - which packages did you update? Do you have any errors in your Unity Console?

**Comment by momo-the-monster** [comment]
Closing due to lack of details.
